line-length = 88
target-version = "py311"

[lint]
# Ignore B008 for FastAPI and Typer dependency injection patterns
ignore = ["B008"]

[lint.per-file-ignores]
# Allow function calls in defaults for FastAPI and Typer files
"src/pycz2/api.py" = ["B008"]
"src/pycz2/cli.py" = ["B008"]